version: '3.9'

services:
  db:
    container_name: wp-mysql
    image: mysql:5.7
    volumes:
       - $PWD/data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: example
       MYSQL_DATABASE: example
       MYSQL_USER: example
       MYSQL_PASSWORD: example
    ports:
      - "3306:3306"
    networks:
      - my_net

  wp:
    container_name: wp-web
    volumes:
      - "$PWD/html:/var/www/html"
    depends_on:
      - db
    image: wordpress
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: example
      WORDPRESS_DB_USER: example
      WORDPRESS_DB_PASSWORD: example
    networks:
      - my_net
networks:
  my_net:
